version: "3.8"
services:
  app:
    hostname: myhobbees
    container_name: myhobbees
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
