name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  ##############################################
  # TERRAFORM - STG (branch: dev)
  ##############################################
  terraform-fronts-stg:
    name: Terraform Fronts (stg)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install boto3
      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
      - name: Run Terraform
        run: python3.14 infrastructure/scripts/terraform.py fronts stg
        env:
          AWS__TFSTATE_BUCKET: ${{ secrets.AWS__TFSTATE_BUCKET }}
          AWS__TFSTATE_REGION: ${{ secrets.AWS__TFSTATE_REGION }}
          TF_STG__AWS_ACCESS_KEY: ${{ secrets.TF_STG__AWS_ACCESS_KEY }}
          TF_STG__AWS_SECRET_KEY: ${{ secrets.TF_STG__AWS_SECRET_KEY }}

  ##############################################
  # DEPLOY - STG (branch: dev)
  ##############################################
  deploy-assets-stg:
    name: Deploy Assets (stg)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Install dependencies
        run: pip install boto3
      - name: Deploy
        run: python3.14 infrastructure/scripts/deploy.folder.py assets stg
        env:
          TF_STG__AWS_ACCESS_KEY: ${{ secrets.TF_STG__AWS_ACCESS_KEY }}
          TF_STG__AWS_SECRET_KEY: ${{ secrets.TF_STG__AWS_SECRET_KEY }}

  deploy-back-office-stg:
    name: Deploy Back Office (stg)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Install dependencies
        run: pip install boto3
      - name: Deploy
        run: python3.14 infrastructure/scripts/deploy.folder.py www-back-office stg
        env:
          TF_STG__AWS_ACCESS_KEY: ${{ secrets.TF_STG__AWS_ACCESS_KEY }}
          TF_STG__AWS_SECRET_KEY: ${{ secrets.TF_STG__AWS_SECRET_KEY }}

  ##############################################
  # TERRAFORM - PRD (branch: main)
  ##############################################
  terraform-fronts-prd:
    name: Terraform Fronts (prd)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install boto3
      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
      - name: Run Terraform
        run: python3.14 infrastructure/scripts/terraform.py fronts prd
        env:
          AWS__TFSTATE_BUCKET: ${{ secrets.AWS__TFSTATE_BUCKET }}
          AWS__TFSTATE_REGION: ${{ secrets.AWS__TFSTATE_REGION }}
          TF_PRD__AWS_ACCESS_KEY: ${{ secrets.TF_PRD__AWS_ACCESS_KEY }}
          TF_PRD__AWS_SECRET_KEY: ${{ secrets.TF_PRD__AWS_SECRET_KEY }}

  ##############################################
  # DEPLOY - PRD (branch: main)
  ##############################################
  deploy-assets-prd:
    name: Deploy Assets (prd)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Install dependencies
        run: pip install boto3
      - name: Deploy
        run: python3.14 infrastructure/scripts/deploy.folder.py assets prd
        env:
          TF_PRD__AWS_ACCESS_KEY: ${{ secrets.TF_PRD__AWS_ACCESS_KEY }}
          TF_PRD__AWS_SECRET_KEY: ${{ secrets.TF_PRD__AWS_SECRET_KEY }}

  deploy-back-office-prd:
    name: Deploy Back Office (prd)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Install dependencies
        run: pip install boto3
      - name: Deploy
        run: python3.14 infrastructure/scripts/deploy.folder.py www-back-office prd
        env:
          TF_PRD__AWS_ACCESS_KEY: ${{ secrets.TF_PRD__AWS_ACCESS_KEY }}
          TF_PRD__AWS_SECRET_KEY: ${{ secrets.TF_PRD__AWS_SECRET_KEY }}
