name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  ##############################################
  # TERRAFORM - STG (branch: dev)
  ##############################################
  terraform-fronts-stg:
    name: Terraform Fronts (stg)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install boto3
      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
      - name: Run Terraform
        run: python3.14 infrastructure/scripts/terraform.py fronts stg
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  ##############################################
  # DEPLOY - STG (branch: dev)
  ##############################################
  deploy-assets-stg:
    name: Deploy Assets (stg)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Install dependencies
        run: pip install boto3
      - name: Deploy
        run: python3.14 infrastructure/scripts/deploy.folder.py assets stg
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  ##############################################
  # TERRAFORM - PRD (branch: main)
  ##############################################
  terraform-fronts-prd:
    name: Terraform Fronts (prd)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install boto3
      - name: Install tfenv
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
      - name: Run Terraform
        run: python3.14 infrastructure/scripts/terraform.py fronts prd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  ##############################################
  # DEPLOY - PRD (branch: main)
  ##############################################
  deploy-assets-prd:
    name: Deploy Assets (prd)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
      - name: Install dependencies
        run: pip install boto3
      - name: Deploy
        run: python3.14 infrastructure/scripts/deploy.folder.py assets prd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
